<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_commerace.Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\NewFolder\**" />
    <EmbeddedResource Remove="Services\NewFolder\**" />
    <None Remove="Services\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Commerace.Domain\E-commerace.Domain.csproj" />
    <ProjectReference Include="..\E-commerace.Services.Abstraction\E-commerace.Services.Abstraction.csproj" />
    <ProjectReference Include="..\E-commerace.Shared\E-commerace.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
  </ItemGroup>

</Project>
